---
- name: Install tigervnc ubuntu
  ansible.builtin.apt:
    name:
      - tigervnc-standalone-server
      - tigervnc-common
      - tigervnc-tools
    update_cache: yes
    state: present

- name: Install desktop ubuntu
  ansible.builtin.apt:
    name:
      - xfce4
      - xfce4-goodies
    state: present

- name: add vnc ubuntu user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/bash
    #groups: cdrom,sudo,dip,plugdev,lxd,lpadmin,sambashare 
    groups: cdrom,sudo,dip,plugdev,lxd

    append: yes
  when: add_vnc_user
